name : Push code to EC2 imaage
on:
  push:
    branches: main 
jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout Code
        uses: actions/checkout@v4
      - name : List directory
        run : ls -al 
